project_id = "ltmfvbcazebowndigkyi"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.send-email]
    verify_jwt = false

