project_id = "ltmfvbcazebowndigkyi"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false

  [functions.preview-transactional-email]
    verify_jwt = false

  [functions.notify-user]
    verify_jwt = false

  [functions.check-payment-status]
    verify_jwt = false

  [functions.create-upload-url]
    verify_jwt = false

  [functions.reconcile-payments]
    verify_jwt = false



