import 'react-native-url-polyfill/auto';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import Constants from 'expo-constants';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import { StatusBar as ExpoStatusBar } from 'expo-status-bar';
import { createClient, Session } from '@supabase/supabase-js';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, AppState, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View } from 'react-native';

type Period = 'day' | 'week' | 'month';
type Tab = 'home' | 'statistics' | 'valid' | 'participants';
type Registration = { id:string; full_name:string; token:string; kind:string; email:string; created_at:string; fast_track:boolean; payment_status:string|null; status:string|null; extra:Record<string,unknown>|null };
type Payment = { id:string; registration_id:string; amount:number; status:string; provider:string|null; created_at:string; registration?:Registration };
type Extra = { supabaseUrl?:string; supabasePublishableKey?:string; easProjectId?:string };

const X=(Constants.expoConfig?.extra??{}) as Extra;
const supabase=createClient(X.supabaseUrl??'',X.supabasePublishableKey??'',{auth:{storage:AsyncStorage,autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});
const C={blue:'#4D7DF3',dark:'#315FCC',soft:'#EDF3FF',navy:'#14213D',text:'#182035',muted:'#7B8498',line:'#E8EBF2',page:'#F5F7FB',white:'#FFF',green:'#20B77A',greenSoft:'#E9FAF3',gold:'#F4AE2B',goldSoft:'#FFF6E3',purple:'#8267DE'};
const SOUND_KEY='prestasi-kita-notification-sound'; let soundOn=true;
Notifications.setNotificationHandler({handleNotification:async()=>({shouldPlaySound:soundOn,shouldSetBadge:true,shouldShowBanner:true,shouldShowList:true})});
const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const kind=(v?:string)=>({prestasi:'Prestasi',ekonomi:'Ekonomi',umum:'Umum',yatim:'Yatim'}[v??'']??v??'-');
const tier=(r?:Registration)=>!r?.fast_track?'Reguler':r.extra?.fast_track_type==='premium'?'FT Premium':'FT Standard';
const date=(v:string)=>new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
function startOf(p:Period){const d=new Date();if(p==='day')d.setHours(0,0,0,0);if(p==='week'){const n=d.getDay()||7;d.setDate(d.getDate()-n+1);d.setHours(0,0,0,0)}if(p==='month'){d.setDate(1);d.setHours(0,0,0,0)}return d}

async function channels(){if(Platform.OS!=='android')return;await Notifications.setNotificationChannelAsync('payments_sound',{name:'Pembayaran dengan suara',importance:Notifications.AndroidImportance.MAX,vibrationPattern:[0,250,150,350],sound:'default',enableVibrate:true});await Notifications.setNotificationChannelAsync('payments_silent',{name:'Pembayaran tanpa suara',importance:Notifications.AndroidImportance.DEFAULT,sound:null,enableVibrate:false})}
async function registerPush(uid:string,enabled:boolean){if(!Device.isDevice)return false;await channels();let {status}=await Notifications.getPermissionsAsync();if(status!=='granted')status=(await Notifications.requestPermissionsAsync()).status;if(status!=='granted')return false;if(!X.easProjectId)return true;const token=(await Notifications.getExpoPushTokenAsync({projectId:X.easProjectId})).data;const{error}=await supabase.from('admin_push_devices').upsert({user_id:uid,push_token:token,platform:Platform.OS,sound_enabled:enabled,active:true,updated_at:new Date().toISOString()},{onConflict:'push_token'});if(error)throw error;return true}

function Splash(){return <View style={s.splash}><ExpoStatusBar style="dark"/><View style={s.splashLogo}><Image source={require('./assets/prestasi-kita-icon.png')} style={s.logo}/></View><Text style={s.splashTitle}>Prestasi Kita</Text><Text style={s.splashSub}>Admin Financial Dashboard</Text><ActivityIndicator color={C.blue} size="large" style={{marginTop:30}}/><Text style={s.loadingText}>Menyiapkan data terbaru...</Text></View>}

function Login({done}:{done:(x:Session)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[hide,setHide]=useState(true);const[busy,setBusy]=useState(false);const submit=async()=>{if(!email.trim()||!password)return Alert.alert('Data belum lengkap','Masukkan email dan kata sandi admin.');setBusy(true);const{data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error||!data.session){setBusy(false);return Alert.alert('Login gagal',error?.message??'Sesi tidak ditemukan.')}const{data:role}=await supabase.from('user_roles').select('role').eq('user_id',data.session.user.id).eq('role','admin').maybeSingle();if(!role){await supabase.auth.signOut();setBusy(false);return Alert.alert('Akses ditolak','Akun ini bukan administrator.')}setBusy(false);done(data.session)};return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.login}><ExpoStatusBar style="dark"/><View style={s.loginLogo}><Image source={require('./assets/prestasi-kita-icon.png')} style={s.logo}/></View><Text style={s.loginTitle}>Selamat datang kembali</Text><Text style={s.loginSub}>Pantau pendapatan dan peserta Prestasi Kita dalam satu aplikasi.</Text><View style={s.loginCard}><Text style={s.inputLabel}>Email administrator</Text><View style={s.inputWrap}><Ionicons name="mail-outline" size={19} color={C.muted}/><TextInput autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="admin@prestasikita.com" placeholderTextColor="#A4ABBA" style={s.input}/></View><Text style={[s.inputLabel,{marginTop:15}]}>Kata sandi</Text><View style={s.inputWrap}><Ionicons name="lock-closed-outline" size={19} color={C.muted}/><TextInput autoCapitalize="none" value={password} onChangeText={setPassword} onSubmitEditing={submit} placeholder="Kata sandi" placeholderTextColor="#A4ABBA" secureTextEntry={hide} style={s.input}/><Pressable onPress={()=>setHide(v=>!v)}><Ionicons name={hide?'eye-outline':'eye-off-outline'} size={20} color={C.muted}/></Pressable></View><Pressable onPress={submit} style={s.loginButton}>{busy?<ActivityIndicator color="white"/>:<><Text style={s.loginButtonText}>Masuk</Text><Ionicons name="arrow-forward" size={19} color="white"/></>}</Pressable></View></KeyboardAvoidingView>}

function Segment({value,set}:{value:Period;set:(v:Period)=>void}){return <View style={s.segment}>{(['day','week','month'] as Period[]).map(v=><Pressable key={v} onPress={()=>set(v)} style={[s.segmentItem,value===v&&s.segmentActive]}><Text style={[s.segmentText,value===v&&s.segmentTextActive]}>{v==='day'?'Harian':v==='week'?'Mingguan':'Bulanan'}</Text></Pressable>)}</View>}
function Badge({r}:{r?:Registration}){const t=tier(r),p=t==='FT Premium',f=t==='FT Standard';return <View style={[s.badge,p?s.premium:f?s.standard:s.regular]}><Text style={[s.badgeText,{color:p?'#B87300':f?C.dark:C.muted}]}>{t}</Text></View>}
function PaymentRow({p}:{p:Payment}){return <View style={s.row}><View style={[s.avatar,{backgroundColor:C.greenSoft}]}><Ionicons name="checkmark" size={19} color={C.green}/></View><View style={s.rowMain}><Text numberOfLines={1} style={s.rowTitle}>{p.registration?.full_name??'Peserta'}</Text><Text numberOfLines={1} style={s.rowSub}>{p.registration?.token??'-'} · {kind(p.registration?.kind)}</Text><Text style={s.rowDate}>{date(p.created_at)}</Text></View><View style={s.rowRight}><Text style={s.income}>+{rupiah(p.amount)}</Text><Badge r={p.registration}/></View></View>}
function RegistrationRow({r}:{r:Registration}){return <View style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{r.full_name?.slice(0,1).toUpperCase()||'P'}</Text></View><View style={s.rowMain}><Text numberOfLines={1} style={s.rowTitle}>{r.full_name}</Text><Text numberOfLines={1} style={s.rowSub}>{r.token} · {kind(r.kind)}</Text><Text style={s.rowDate}>{date(r.created_at)}</Text></View><Badge r={r}/></View>}
function ListCard({title,sub,children,empty}:{title:string;sub:string;children:React.ReactNode;empty:boolean}){return <View style={s.card}><View style={s.cardHead}><View><Text style={s.cardTitle}>{title}</Text><Text style={s.cardSub}>{sub}</Text></View><View style={s.live}><View style={s.liveDot}/><Text style={s.liveText}>LIVE</Text></View></View>{empty?<View style={s.empty}><Ionicons name="file-tray-outline" size={34} color="#B3BAC8"/><Text style={s.emptyText}>Belum ada data</Text></View>:<ScrollView nestedScrollEnabled showsVerticalScrollIndicator style={s.innerList}>{children}</ScrollView>}</View>}
function Mini({icon,label,value,color,bg}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;color:string;bg:string}){return <View style={s.mini}><View style={[s.miniIcon,{backgroundColor:bg}]}><Ionicons name={icon} size={20} color={color}/></View><Text style={s.miniValue}>{value}</Text><Text style={s.miniLabel}>{label}</Text></View>}

function Chart({payments,period}:{payments:Payment[];period:Period}){const pts=useMemo(()=>{const count=period==='day'?8:period==='week'?7:6;return Array.from({length:count},(_,i)=>{const now=new Date();let from=new Date(),to=new Date(),label='';if(period==='day'){const h=Math.floor(now.getHours()/3)*3-(count-1-i)*3;from=new Date(now);from.setHours(h,0,0,0);to=new Date(from);to.setHours(from.getHours()+3);label=String((h+24)%24).padStart(2,'0')}else if(period==='week'){from=new Date(now);from.setDate(now.getDate()-(count-1-i));from.setHours(0,0,0,0);to=new Date(from);to.setDate(from.getDate()+1);label=from.toLocaleDateString('id-ID',{weekday:'short'}).slice(0,3)}else{from=new Date(now.getFullYear(),now.getMonth()-(count-1-i),1);to=new Date(from.getFullYear(),from.getMonth()+1,1);label=from.toLocaleDateString('id-ID',{month:'short'}).slice(0,3)}const total=payments.filter(p=>{const d=new Date(p.created_at);return d>=from&&d<to}).reduce((a,p)=>a+Number(p.amount||0),0);return{label,total}})},[payments,period]);const max=Math.max(...pts.map(p=>p.total),1);return <View style={s.chart}>{pts.map((p,i)=><View key={`${p.label}${i}`} style={s.chartCol}><Text style={s.chartNum}>{p.total?`${Math.round(p.total/1000)}k`:'0'}</Text><View style={s.chartTrack}><View style={[s.chartBar,{height:Math.max(6,(p.total/max)*100),backgroundColor:i===pts.length-1?C.gold:C.blue}]}/></View><Text style={s.chartLabel}>{p.label}</Text></View>)}</View>}
function Nav({tab,set}:{tab:Tab;set:(v:Tab)=>void}){const items:[Tab,keyof typeof Ionicons.glyphMap,string][]=[['home','grid','Dashboard'],['statistics','stats-chart','Statistik'],['valid','shield-checkmark','Valid'],['participants','people','Peserta']];return <View style={s.nav}>{items.map(([k,i,l])=><Pressable key={k} onPress={()=>set(k)} style={s.navItem}><View style={[s.navIcon,tab===k&&s.navActive]}><Ionicons name={i} size={21} color={tab===k?'white':'#9AA3B4'}/></View><Text style={[s.navText,tab===k&&{color:C.dark}]}>{l}</Text></Pressable>)}</View>}

function Dashboard({session,logout}:{session:Session;logout:()=>void}){const[tab,setTab]=useState<Tab>('home');const[period,setPeriod]=useState<Period>('day');const[payments,setPayments]=useState<Payment[]>([]);const[regs,setRegs]=useState<Registration[]>([]);const[total,setTotal]=useState(0);const[today,setToday]=useState(0);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[sound,setSound]=useState(true);const[notice,setNotice]=useState<string|null>(null);const mounted=useRef(true);
 const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);const since=new Date();since.setMonth(since.getMonth()-7);const day=startOf('day').toISOString();const[pr,rr,tr,dr]=await Promise.all([supabase.from('payments').select('id,registration_id,amount,status,provider,created_at').eq('status','paid').gte('created_at',since.toISOString()).order('created_at',{ascending:false}).limit(2000),supabase.from('registrations').select('id,full_name,token,kind,email,created_at,fast_track,payment_status,status,extra').order('created_at',{ascending:false}).limit(300),supabase.from('registrations').select('id',{count:'exact',head:true}),supabase.from('registrations').select('id',{count:'exact',head:true}).gte('created_at',day)]);if(pr.error||rr.error){if(mounted.current){setLoading(false);setRefreshing(false)}return Alert.alert('Data gagal dimuat',pr.error?.message??rr.error?.message??'Terjadi kesalahan.')}const rs=(rr.data??[]) as Registration[];const map=new Map(rs.map(r=>[r.id,r]));const missing=Array.from(new Set((pr.data??[]).map(p=>p.registration_id).filter(id=>!map.has(id))));for(let i=0;i<missing.length;i+=200){const{data}=await supabase.from('registrations').select('id,full_name,token,kind,email,created_at,fast_track,payment_status,status,extra').in('id',missing.slice(i,i+200));(data??[]).forEach(r=>map.set(r.id,r as Registration))}if(mounted.current){setRegs(rs);setTotal(tr.count??rs.length);setToday(dr.count??0);setPayments(((pr.data??[]) as Payment[]).map(p=>({...p,registration:map.get(p.registration_id)})));setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{mounted.current=true;AsyncStorage.getItem(SOUND_KEY).then(v=>{const enabled=v!=='false';soundOn=enabled;setSound(enabled);registerPush(session.user.id,enabled).catch(console.warn)});channels();load();const ch=supabase.channel(`mobile-admin-${session.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'payments',filter:'status=eq.paid'},async e=>{await load(true);const row=e.new as Payment;const message=`${rupiah(Number(row.amount))} berhasil diverifikasi.`;setNotice(message);setTimeout(()=>{if(mounted.current)setNotice(null)},5000);await Notifications.scheduleNotificationAsync({content:{title:'Pembayaran baru masuk 💰',body:message,sound:soundOn?'default':undefined,priority:Notifications.AndroidNotificationPriority.MAX,data:{type:'payment_paid',registration_id:row.registration_id}},trigger:Platform.OS==='android'?{channelId:soundOn?'payments_sound':'payments_silent'}:null})}).on('postgres_changes',{event:'INSERT',schema:'public',table:'registrations'},()=>load(true)).subscribe();const app=AppState.addEventListener('change',v=>{if(v==='active')load(true)});return()=>{mounted.current=false;app.remove();supabase.removeChannel(ch)}},[load,session.user.id]);
 const toggle=async(v:boolean)=>{setSound(v);soundOn=v;await AsyncStorage.setItem(SOUND_KEY,String(v));await channels();await supabase.from('admin_push_devices').update({sound_enabled:v,updated_at:new Date().toISOString()}).eq('user_id',session.user.id)};
 const fp=payments.filter(p=>new Date(p.created_at)>=startOf(period));const income=fp.reduce((a,p)=>a+Number(p.amount||0),0);const valid=fp.map(p=>p.registration).filter(Boolean) as Registration[];const standard=valid.filter(r=>tier(r)==='FT Standard').length,premium=valid.filter(r=>tier(r)==='FT Premium').length;const title=tab==='home'?'Dashboard Utama':tab==='statistics'?'Statistik Pendapatan':tab==='valid'?'Peserta Valid':'Seluruh Pendaftar';
 const body=()=>{if(loading)return <View style={s.loading}><ActivityIndicator size="large" color={C.blue}/><Text style={s.loadingText}>Mengambil data terbaru...</Text></View>;if(tab==='home')return <><View style={s.balance}><View style={s.balanceTop}><Text style={s.balanceLabel}>Total Pendapatan</Text><Text style={s.balanceBrand}>PRESTASI KITA</Text></View><Text style={s.balanceValue}>{rupiah(income)}</Text><View style={s.balanceBottom}><View><Text style={s.balanceSmall}>PESERTA VALID</Text><Text style={s.balanceCount}>{fp.length} peserta</Text></View><Ionicons name="wallet" size={29} color="white"/></View></View><Segment value={period} set={setPeriod}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quick}><Mini icon="people" color={C.blue} bg={C.soft} label="Total Pendaftar" value={String(total)}/><Mini icon="person-add" color={C.purple} bg="#F1EDFF" label="Pendaftar Hari Ini" value={String(today)}/><Mini icon="flash" color={C.gold} bg={C.goldSoft} label="FT Standard" value={String(standard)}/><Mini icon="diamond" color={C.green} bg={C.greenSoft} label="FT Premium" value={String(premium)}/></ScrollView><ListCard title="Pembayaran Terbaru" sub="Daftar scroll di dalam card" empty={!fp.length}>{fp.slice(0,40).map(p=><PaymentRow key={p.id} p={p}/>)}</ListCard></>;
 if(tab==='statistics')return <><Segment value={period} set={setPeriod}/><View style={s.card}><View style={s.cardHead}><View><Text style={s.cardTitle}>Grafik Pendapatan</Text><Text style={s.cardSub}>Ringkasan transaksi berhasil</Text></View><Ionicons name="analytics" size={23} color={C.blue}/></View><Chart payments={payments} period={period}/></View><View style={s.summary}><View style={s.summaryBox}><Text style={s.summaryLabel}>TOTAL PENDAPATAN</Text><Text style={s.summaryAmount}>{rupiah(income)}</Text></View><View style={s.summaryBox}><Text style={s.summaryLabel}>TRANSAKSI VALID</Text><Text style={s.summaryNumber}>{fp.length}</Text></View></View><ListCard title="Riwayat Transaksi" sub="Scroll di dalam card" empty={!fp.length}>{fp.slice(0,60).map(p=><PaymentRow key={p.id} p={p}/>)}</ListCard></>;
 if(tab==='valid')return <><Segment value={period} set={setPeriod}/><View style={s.validHero}><View><Text style={s.heroLabel}>Peserta valid periode ini</Text><Text style={s.heroNumber}>{fp.length}</Text></View><View><Text style={s.heroTier}>Standard  {standard}</Text><Text style={s.heroTier}>Premium  {premium}</Text></View></View><ListCard title="Fast Track Standard & Premium" sub="Pembayaran terverifikasi" empty={!fp.length}>{fp.slice(0,80).map(p=><PaymentRow key={p.id} p={p}/>)}</ListCard></>;
 return <><View style={s.partHero}><Text style={s.heroLabel}>Total seluruh pendaftar</Text><Text style={s.partNumber}>{total}</Text><Text style={s.partSub}>+{today} pendaftar hari ini</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{['Reguler','FT Standard','FT Premium'].map(t=><View key={t} style={s.chip}><Text style={s.chipText}>{t} {regs.filter(r=>tier(r)===t).length}</Text></View>)}</ScrollView><ListCard title="Pendaftar Terbaru" sub="300 data terbaru · scroll di dalam card" empty={!regs.length}>{regs.map(r=><RegistrationRow key={r.id} r={r}/>)}</ListCard></>};
 return <SafeAreaView style={s.page}><ExpoStatusBar style="dark"/><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} colors={[C.blue]} onRefresh={()=>{setRefreshing(true);load(true)}}/>}>{notice&&<View style={s.notice}><View style={s.noticeIcon}><Ionicons name="wallet" size={21} color="white"/></View><View style={{flex:1}}><Text style={s.noticeTitle}>Pembayaran baru masuk</Text><Text style={s.noticeBody}>{notice}</Text></View><Pressable onPress={()=>setNotice(null)}><Ionicons name="close" size={20} color="white"/></Pressable></View>}<View style={s.header}><View style={{flex:1}}><Text style={s.eyebrow}>PRESTASI KITA ADMIN</Text><Text style={s.headerTitle}>{title}</Text><Text style={s.headerDate}>{new Date().toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'numeric',month:'long',year:'numeric'})}</Text></View><Pressable style={s.headerBtn} onPress={()=>Alert.alert('Pengaturan','Kelola notifikasi atau keluar.',[{text:'Tes notifikasi',onPress:async()=>{const ok=await registerPush(session.user.id,sound);if(!ok)return Alert.alert('Izin diperlukan','Aktifkan izin notifikasi Prestasi Kita di pengaturan Android.');await Notifications.scheduleNotificationAsync({content:{title:'Tes pembayaran masuk 💰',body:'Notifikasi pop-up dan suara berhasil diaktifkan.',sound:sound?'default':undefined,priority:Notifications.AndroidNotificationPriority.MAX},trigger:Platform.OS==='android'?{channelId:sound?'payments_sound':'payments_silent'}:null})}},{text:sound?'Matikan suara':'Aktifkan suara',onPress:()=>toggle(!sound)},{text:'Keluar',style:'destructive',onPress:logout},{text:'Batal',style:'cancel'}])}><Ionicons name={sound?'notifications':'notifications-off'} size={21} color={C.blue}/></Pressable></View>{body()}</ScrollView><Nav tab={tab} set={setTab}/></SafeAreaView>}

export default function App(){const[session,setSession]=useState<Session|null>(null);const[init,setInit]=useState(true);useEffect(()=>{const started=Date.now();supabase.auth.getSession().then(async({data})=>{let valid:Session|null=null;if(data.session){const{data:role}=await supabase.from('user_roles').select('role').eq('user_id',data.session.user.id).eq('role','admin').maybeSingle();if(role)valid=data.session}setTimeout(()=>{setSession(valid);setInit(false)},Math.max(0,1600-(Date.now()-started)))});const{data}=supabase.auth.onAuthStateChange((_e,n)=>{if(!n)setSession(null)});return()=>data.subscription.unsubscribe()},[]);if(init)return <Splash/>;if(!session)return <Login done={setSession}/>;return <Dashboard session={session} logout={async()=>{await supabase.from('admin_push_devices').update({active:false,updated_at:new Date().toISOString()}).eq('user_id',session.user.id);await supabase.auth.signOut();setSession(null)}}/>}

const s=StyleSheet.create({
 page:{flex:1,backgroundColor:C.page},content:{paddingHorizontal:18,paddingTop:Platform.OS==='android'?(StatusBar.currentHeight??24)+14:18,paddingBottom:120},splash:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'white'},splashLogo:{width:118,height:118,borderRadius:34,overflow:'hidden',shadowColor:C.blue,shadowOpacity:.18,shadowRadius:22,elevation:8},logo:{width:'100%',height:'100%',resizeMode:'cover'},splashTitle:{marginTop:24,color:C.navy,fontSize:28,fontWeight:'900'},splashSub:{marginTop:5,color:C.muted,fontSize:12,letterSpacing:.8},loadingText:{marginTop:12,color:C.muted,fontSize:11},
 login:{flex:1,justifyContent:'center',paddingHorizontal:24,paddingTop:Platform.OS==='android'?StatusBar.currentHeight:0,backgroundColor:C.page},loginLogo:{width:76,height:76,borderRadius:24,overflow:'hidden'},loginTitle:{marginTop:24,color:C.navy,fontSize:28,fontWeight:'900'},loginSub:{marginTop:8,color:C.muted,fontSize:13,lineHeight:20},loginCard:{marginTop:25,padding:20,borderRadius:25,backgroundColor:'white',borderWidth:1,borderColor:C.line},inputLabel:{marginBottom:7,color:C.text,fontSize:11,fontWeight:'800'},inputWrap:{height:52,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10,borderRadius:15,backgroundColor:'#F9FAFC',borderWidth:1,borderColor:C.line},input:{flex:1,height:'100%',color:C.text},loginButton:{height:53,marginTop:22,flexDirection:'row',gap:9,alignItems:'center',justifyContent:'center',borderRadius:16,backgroundColor:C.blue},loginButtonText:{color:'white',fontWeight:'900'},
 header:{minHeight:80,flexDirection:'row',alignItems:'flex-start',gap:12,marginBottom:17},eyebrow:{color:C.blue,fontSize:9,fontWeight:'900',letterSpacing:1.3},headerTitle:{marginTop:5,color:C.navy,fontSize:25,fontWeight:'900'},headerDate:{marginTop:4,color:C.muted,fontSize:11},headerBtn:{width:45,height:45,alignItems:'center',justifyContent:'center',borderRadius:15,backgroundColor:'white',borderWidth:1,borderColor:C.line},
 balance:{height:188,padding:21,borderRadius:27,backgroundColor:C.blue,shadowColor:C.blue,shadowOpacity:.24,shadowRadius:16,elevation:7},balanceTop:{flexDirection:'row',justifyContent:'space-between'},balanceLabel:{color:'rgba(255,255,255,.82)',fontSize:12,fontWeight:'700'},balanceBrand:{color:'white',fontSize:9,fontWeight:'900'},balanceValue:{marginTop:20,color:'white',fontSize:31,fontWeight:'900'},balanceBottom:{marginTop:'auto',flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},balanceSmall:{color:'rgba(255,255,255,.66)',fontSize:8,fontWeight:'800'},balanceCount:{marginTop:3,color:'white',fontSize:13,fontWeight:'800'},
 segment:{marginTop:17,padding:4,flexDirection:'row',borderRadius:15,backgroundColor:'#E9EDF5'},segmentItem:{flex:1,height:36,alignItems:'center',justifyContent:'center',borderRadius:12},segmentActive:{backgroundColor:'white',elevation:2},segmentText:{color:C.muted,fontSize:10,fontWeight:'800'},segmentTextActive:{color:C.dark},quick:{gap:11,paddingVertical:17},mini:{width:126,padding:14,borderRadius:19,backgroundColor:'white',borderWidth:1,borderColor:C.line},miniIcon:{width:39,height:39,borderRadius:13,alignItems:'center',justifyContent:'center'},miniValue:{marginTop:12,color:C.navy,fontSize:21,fontWeight:'900'},miniLabel:{marginTop:3,color:C.muted,fontSize:9.5,fontWeight:'700'},
 card:{marginTop:16,padding:17,borderRadius:24,backgroundColor:'white',borderWidth:1,borderColor:C.line},cardHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},cardTitle:{color:C.navy,fontSize:15,fontWeight:'900'},cardSub:{marginTop:3,color:C.muted,fontSize:9.5},live:{flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:8,paddingVertical:5,borderRadius:20,backgroundColor:C.greenSoft},liveDot:{width:6,height:6,borderRadius:3,backgroundColor:C.green},liveText:{color:C.green,fontSize:8,fontWeight:'900'},innerList:{maxHeight:365},
 row:{minHeight:72,paddingVertical:11,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#F0F2F6'},avatar:{width:41,height:41,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.soft},avatarText:{color:C.dark,fontWeight:'900'},rowMain:{flex:1,minWidth:0,marginHorizontal:10},rowTitle:{color:C.text,fontSize:12,fontWeight:'900'},rowSub:{marginTop:3,color:C.muted,fontSize:9.5},rowDate:{marginTop:3,color:'#A0A7B6',fontSize:8.5},rowRight:{maxWidth:130,alignItems:'flex-end'},income:{marginBottom:5,color:C.green,fontSize:10.5,fontWeight:'900'},badge:{paddingHorizontal:7,paddingVertical:4,borderRadius:9},premium:{backgroundColor:C.goldSoft},standard:{backgroundColor:C.soft},regular:{backgroundColor:'#F1F3F6'},badgeText:{fontSize:7.5,fontWeight:'900'},
 chart:{height:175,flexDirection:'row',alignItems:'flex-end',gap:6},chartCol:{flex:1,alignItems:'center'},chartNum:{height:17,color:C.muted,fontSize:7.5,fontWeight:'700'},chartTrack:{width:'62%',height:105,justifyContent:'flex-end',overflow:'hidden',borderRadius:8,backgroundColor:'#F0F3F8'},chartBar:{width:'100%',borderRadius:8},chartLabel:{marginTop:7,color:C.muted,fontSize:8.5,fontWeight:'700'},summary:{marginTop:14,flexDirection:'row',gap:10},summaryBox:{flex:1,minHeight:95,padding:15,borderRadius:20,backgroundColor:'white',borderWidth:1,borderColor:C.line},summaryLabel:{color:C.muted,fontSize:8,fontWeight:'900'},summaryAmount:{marginTop:12,color:C.dark,fontSize:17,fontWeight:'900'},summaryNumber:{marginTop:9,color:C.green,fontSize:25,fontWeight:'900'},
 validHero:{marginTop:16,padding:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderRadius:23,backgroundColor:C.navy},heroLabel:{color:'rgba(255,255,255,.68)',fontSize:10},heroNumber:{marginTop:5,color:'white',fontSize:32,fontWeight:'900'},heroTier:{marginVertical:4,color:'white',fontSize:10,fontWeight:'800'},partHero:{padding:21,borderRadius:24,backgroundColor:C.blue},partNumber:{marginTop:5,color:'white',fontSize:36,fontWeight:'900'},partSub:{marginTop:5,color:'white',fontSize:11,fontWeight:'700'},chips:{gap:8,paddingTop:13},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:20,backgroundColor:'white',borderWidth:1,borderColor:C.line},chipText:{color:C.text,fontSize:9.5,fontWeight:'800'},
 notice:{marginBottom:14,padding:14,flexDirection:'row',alignItems:'center',gap:11,borderRadius:18,backgroundColor:C.green,shadowColor:C.green,shadowOpacity:.25,shadowRadius:12,elevation:6},noticeIcon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.18)'},noticeTitle:{color:'white',fontSize:12,fontWeight:'900'},noticeBody:{marginTop:3,color:'rgba(255,255,255,.88)',fontSize:10},nav:{position:'absolute',left:14,right:14,bottom:Platform.OS==='ios'?20:13,height:76,paddingHorizontal:7,flexDirection:'row',alignItems:'center',borderRadius:25,backgroundColor:'white',borderWidth:1,borderColor:C.line,shadowColor:C.navy,shadowOpacity:.13,shadowRadius:17,elevation:12},navItem:{flex:1,alignItems:'center'},navIcon:{width:38,height:34,alignItems:'center',justifyContent:'center',borderRadius:13},navActive:{backgroundColor:C.blue},navText:{marginTop:3,color:'#9AA3B4',fontSize:7.5,fontWeight:'800'},loading:{height:420,alignItems:'center',justifyContent:'center'},empty:{height:160,alignItems:'center',justifyContent:'center'},emptyText:{marginTop:9,color:C.muted,fontSize:11,fontWeight:'700'}
});
